let me=null,favs=[],selected=null,lastPage='home';
const socket = io();
socket.on('connect',()=>console.log('Real-Time Bid connected'));
socket.on('auction:bid',(auction)=>handleRealtimeAuction(auction,'bid'));
socket.on('auction:update',(auction)=>handleRealtimeAuction(auction,'update'));
socket.on('auction:chat',(auction)=>handleRealtimeAuction(auction,'chat'));
socket.on('auction:timer',(auction)=>handleRealtimeAuction(auction,'timer'));
socket.on('auction:closed',(auction)=>handleRealtimeAuction(auction,'closed'));
socket.on('order:update',()=>{ if(!orders.classList.contains('hidden')) loadOrders('all'); });
function handleRealtimeAuction(auction,eventType){
  if(!auction) return;
  if(selected===auction.id && !room.classList.contains('hidden')) openRoom(auction.id);
  if(!home.classList.contains('hidden')) loadAuctions('general');
  if(!vipzone.classList.contains('hidden')) loadAuctions('vip');
  if(!favorites.classList.contains('hidden')) loadFavs();
}
const pages={home:'หน้าหลัก',vipzone:'VIP Zone',sell:'ลงสินค้า',estimate:'ประเมิณราคา',wallet:'กระเป๋าเงิน',orders:'คำสั่งซื้อ / Escrow',favorites:'รายการที่สนใจ',profile:'บัญชีผู้ใช้',vip:'สมัคร VIP',ads:'ดูโฆษณา',createAd:'ลงโฆษณา',chat:'สนทนา',reviews:'รีวิว',admin:'Admin',room:'หน้าประมูล',login:'เข้าสู่ระบบ',register:'สมัครสมาชิก',rules:'กฏ/เงื่อนไข'};function $(id){return document.getElementById(id)}function money(n,c){return Number(n||0).toLocaleString('th-TH')+' '+c}async function api(u,o={}){let r=await fetch(u,{headers:{'Content-Type':'application/json'},...o}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'ผิดพลาด');return j}function av(u){let n=u?(u.display_name||u.username):'Guest';return u&&u.avatar_url?u.avatar_url:`https://ui-avatars.com/api/?name=${encodeURIComponent(n)}&background=111827&color=fff`}
async function loadMe(){me=(await api('/api/me')).user}function header(){document.body.classList.toggle('admin',!!(me&&me.role==='admin'));auth.innerHTML=me?`<button onclick="show('profile')" class="userChip"><img src="${av(me)}">${me.display_name||me.username}</button>${me.role==='admin'?`<button class="gold" onclick="showAdmin()">Admin</button>`:''}<button class="danger" onclick="logout()">ออกจากระบบ</button>`:`<button class="light" onclick="show('login')">เข้าสู่ระบบ</button><button class="gold" onclick="show('register')">สมัครสมาชิก</button>`;sideAvatar.src=av(me);sideName.textContent=me?(me.display_name||me.username):'Guest';sideStatus.textContent=me?(me.role==='admin'?'Admin':(me.is_vip?'สมาชิก VIP':'สมาชิกทั่วไป')):'กรุณาเข้าสู่ระบบ'}async function refresh(){await loadMe();header();await loadFavIds();renderWallet();if(!home.classList.contains('hidden'))loadAuctions('general');if(!vipzone.classList.contains('hidden'))loadAuctions('vip');if(!favorites.classList.contains('hidden'))loadFavs();if(!orders.classList.contains('hidden'))loadOrders('all');if(!reviews.classList.contains('hidden'))loadReviews();if(!estimate.classList.contains('hidden'))loadEstHistory();if(!profile.classList.contains('hidden'))renderProfile();if(!admin.classList.contains('hidden'))loadAdmin();renderHearts()}function show(id){if(id==='admin')return showAdmin();if(id==='orders'&&(!me||me.role!=='admin'))return showAdmin();Object.keys(pages).forEach(p=>$(p)?.classList.add('hidden'));$(id)?.classList.remove('hidden');title.textContent=pages[id]||'BidMarket';desc.textContent='BidMarket';refresh()}function need(){if(!me){show('login');return false}return true}function showVip(){if(need())show('vipzone')}async function login(){try{me=(await api('/api/login',{method:'POST',body:JSON.stringify({username:loginUser.value,password:loginPass.value})})).user;show('home')}catch(e){loginMsg.innerHTML='<div class="notice error">'+e.message+'</div>'}}async function register(){me=(await api('/api/register',{method:'POST',body:JSON.stringify({username:regUser.value,email:regEmail.value,password:regPass.value})})).user;show('home')}async function logout(){await api('/api/logout',{method:'POST'});me=null;show('login')}
async function upload(f){let fd=new FormData();fd.append('file',f);let r=await fetch('/api/upload',{method:'POST',body:fd}),j=await r.json();return j.url}function rulesSell(){let l=sellLevel.value;let ms=l=='general'?[['forward','Forward']]:[['forward','Forward'],['sealed','Sealed']];sellMethod.innerHTML=ms.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('');sellCurrency.innerHTML=(l=='general'?['coin','credit']:['coin','credit','token']).map(x=>`<option value="${x}">${x}</option>`).join('');vipBox.classList.toggle('hidden',l!='vip')}rulesSell();async function createAuction(){if(!need())return;let url=sellUrl.value;if(sellFile.files[0])url=await upload(sellFile.files[0]);await api('/api/auctions',{method:'POST',body:JSON.stringify({level:sellLevel.value,method:sellMethod.value,currency:sellCurrency.value,title:sellTitle.value,description:sellDesc.value,category:sellCategory.value,image_url:url,media_type:mediaType.value,start_price:+sellStart.value,start_at:sellStartAt.value,sealed_hours:+sellHours.value,vip_entry_min_credit:+vipMin.value,vip_entry_fee_percent:+vipFee.value})});sellMsg.innerHTML='<div class="notice success">เพิ่มสินค้าแล้ว</div>'}
async function loadAuctions(level){let j=await api('/api/auctions?level='+level);(level=='general'?generalGrid:vipGrid).innerHTML=j.auctions.map(card).join('')||'<div class="notice">ยังไม่มีสินค้า</div>';renderHearts()}function tleft(ms){let s=Math.floor(ms/1000),d=Math.floor(s/86400);s%=86400;let h=Math.floor(s/3600);s%=3600;let m=Math.floor(s/60);s%=60;return d?d+' วัน':h?h+' ชม.':m?m+' นาที':s+' วิ'}function media(a,cls=''){return a.media_type=='video'?`<video class="${cls}" src="${a.image_url}" controls></video>`:`<img class="${cls}" src="${a.image_url||''}">`}function card(a){let btn=!a.is_started?`<button disabled>เริ่มในอีก ${tleft(a.time_until_start)}</button>`:`<button class="green" onclick="openJoin(${a.id})">เข้าร่วมประมูล</button>`;return `<div class="card auction">${media(a)}<div class="content"><span class="tag ${a.level=='vip'?'vip':''}">${a.level}</span><span class="tag">${a.method}</span><h3>${a.title}</h3><div class="price">${money(a.current_bid,a.currency)}</div><div class="meta"><div>ผู้ขาย: ${a.seller_name}</div><div>Trust: ${a.seller_trust_rate||0}%</div><div>ผู้เสนอราคา: ${a.participant_count}</div></div>${btn}<button class="light" onclick="openRoom(${a.id})">ดูรายละเอียด</button></div><button class="heart" id="heart-${a.id}" onclick="toggleFav(event,${a.id})">♡</button></div>`}
async function openJoin(id){if(!need())return;let a=(await api('/api/auctions/'+id)).auction;joinBody.innerHTML=`<h3>${a.title}</h3>${a.level=='vip'?`<input id="joinCredit" type="number" placeholder="Credit เข้าร่วม">`:''}<button class="green" onclick="confirmJoin(${id})">ยืนยัน</button><button class="light" onclick="openRoom(${id})">ดูรายละเอียด</button>`;joinModal.classList.add('show')}async function confirmJoin(id){await api('/api/auctions/'+id+'/join',{method:'POST',body:JSON.stringify({credit_amount:+($('joinCredit')?.value||0)})});joinModal.classList.remove('show');openRoom(id)}async function openRoom(id){selected=id;lastPage=vipzone.classList.contains('hidden')?'home':'vipzone';let a=(await api('/api/auctions/'+id)).auction;Object.keys(pages).forEach(p=>$(p)?.classList.add('hidden'));room.classList.remove('hidden');title.textContent='หน้าประมูล';roomBody.innerHTML=`<h2>${a.title}</h2>${media(a,'auctionMedia')}<div class="meta"><div>ราคาเริ่ม: ${money(a.start_price,a.currency)}</div><div>ราคาปัจจุบัน: ${money(a.current_bid,a.currency)}</div><div>ผู้เสนอราคา: ${a.participant_count}</div><div>${a.description||''}</div></div><input id="bidAmt" type="number" placeholder="ราคาเสนอ"><button class="green" onclick="bid(${id})">เสนอราคา</button><button class="light" onclick="shareAuction(${id})">แชร์</button><button class="gold" onclick="pinAuction(${id})">ปักหมุด</button><button class="light" onclick="closeAuc(${id})">ปิดประมูล</button><h3>แชทประมูล</h3><div class="chatBox">${(a.chats||[]).map(m=>`<div class="msg sys">${m.text}</div>`).join('')}</div>`}async function bid(id){try{await api('/api/auctions/'+id+'/bid',{method:'POST',body:JSON.stringify({amount:+bidAmt.value})});openRoom(id);refresh()}catch(e){alert(e.message)}}async function closeAuc(id){await api('/api/auctions/'+id+'/close',{method:'POST'});alert('ปิดประมูลแล้ว ระบบสร้าง Order และพักเงิน Escrow แล้ว'); if(me&&me.role==='admin') showAdmin(); else show('home')}
async function shareAuction(id){const url=location.origin+location.pathname+'#auction-'+id;try{if(navigator.share)await navigator.share({title:'BidMarket Auction',url});else await navigator.clipboard.writeText(url);alert('แชร์/คัดลอกลิงก์แล้ว')}catch(e){alert('คัดลอกลิงก์: '+url)}}
async function pinAuction(id){try{let hours=prompt('ต้องการปักหมุดกี่ชั่วโมง? (สูงสุด 168 ชั่วโมง / 7 วัน)','24');if(!hours)return;let j=await api('/api/auctions/'+id+'/pin',{method:'POST',body:JSON.stringify({hours:+hours})});alert(`ปักหมุดสำเร็จ ค่าธรรมเนียม ${j.fee} Credit${j.elite_free?' (ใช้สิทธิ์ Elite ฟรี)':''}`);openRoom(id)}catch(e){alert(e.message)}}

async function loadFavIds(){if(!me){favs=[];return}try{favs=(await api('/api/favorites')).favorite_ids}catch{favs=[]}}async function toggleFav(ev,id){ev.stopPropagation();if(!need())return;if(favs.includes(id))await fetch('/api/favorites/'+id,{method:'DELETE'});else await api('/api/favorites/'+id,{method:'POST'});await loadFavIds();renderHearts();if(!favorites.classList.contains('hidden'))loadFavs()}function renderHearts(){document.querySelectorAll('.heart').forEach(b=>{let id=+b.id.replace('heart-','');b.classList.toggle('saved',favs.includes(id));b.textContent=favs.includes(id)?'♥':'♡'})}async function loadFavs(){let j=await api('/api/favorites');favGrid.innerHTML=j.auctions.map(card).join('')||'<div class="notice">ยังไม่มีรายการที่สนใจ</div>'}
function renderWallet(){if(!me)return;walletBox&&(walletBox.innerHTML=`<div class="notice success">Coin ${money(me.coin,'Coin')} | Credit ${money(me.credit,'Credit')} | VIP: ${me.vip_level||'Member'} ${me.is_vip?'(ใช้งานอยู่)':'(หมดอายุ/ยังไม่ได้ซื้อ)'}</div><div class="notice">VIP Points: ${money(me.vip_points||0,'คะแนน')} | เติมสะสม: ${money(me.lifetime_credit_topup||0,'Credit')}</div>`);loadTx()}async function loadTx(){if(!me||!txBox)return;let j=await api('/api/transactions');txBox.innerHTML=j.transactions.length?`<table><tr><th>รายการ</th><th>จำนวน</th><th>สกุลเงิน</th></tr>${j.transactions.map(t=>`<tr><td>${t.type}</td><td>${t.amount}</td><td>${t.currency}</td></tr>`).join('')}</table>`:'<div class="notice">ยังไม่มีรายการ</div>'}async function buyCoin(){try{let credit=+(coinCredit?.value||0);if(credit<=0)return alert('กรุณากรอกจำนวน Credit ที่ต้องการแลก');if(!confirm(`ยืนยันแลก ${credit} Credit เป็น ${credit*100} Coin?\nหมายเหตุ: Coin ไม่สามารถแลกกลับเป็น Credit ได้`))return;await api('/api/wallet/buy-coin',{method:'POST',body:JSON.stringify({credit})});refresh()}catch(e){alert(e.message)}}
async function createPay(){try{let credit=+(creditAmount?.value||0);if(credit<10)return alert('เติมขั้นต่ำ 10 Credit');let j=await api('/api/payments/create-credit-topup',{method:'POST',body:JSON.stringify({credit})});let p=j.payment;payBox.innerHTML=`<div class="notice success"><b>รายการเติมเงิน</b><br>ต้องชำระ ${p.baht_amount.toLocaleString()} บาท = ${p.credit_amount.toLocaleString()} Credit<br>อัตรา ${p.rate_baht_per_credit||6} บาท / 1 Credit<br>สถานะ: รออัปโหลดสลิป</div><div style="text-align:center"><img src="/assets/payment-qr.jfif" style="max-width:280px;width:100%;border-radius:18px;border:1px solid #ddd"><p>สแกน QR นี้เพื่อโอนเงิน แล้วอัปโหลดสลิปเพื่อให้ Admin ตรวจสอบ</p></div><input id="slip_${p.id}" type="file" accept="image/*,.pdf"><button class="green" onclick="uploadSlip('${p.id}')">อัปโหลดสลิปแจ้งชำระเงิน</button>`}catch(e){alert(e.message)}}
async function uploadSlip(id){let inp=document.getElementById('slip_'+id);if(!inp||!inp.files[0])return alert('กรุณาเลือกไฟล์สลิป');let fd=new FormData();fd.append('payment_id',id);fd.append('slip',inp.files[0]);let r=await fetch('/api/payments/upload-slip',{method:'POST',body:fd});let j=await r.json();if(!r.ok)return alert(j.error||'อัปโหลดไม่สำเร็จ');payBox.innerHTML='<div class="notice success">ส่งสลิปแล้ว กรุณารอ Admin ตรวจสอบ เมื่ออนุมัติแล้ว Credit จะเพิ่มเข้าบัญชีอัตโนมัติ</div>';refresh()}
async function mockPay(id){alert('ระบบ Mock ถูกปิดแล้ว ใช้การอัปโหลดสลิปและรอ Admin อนุมัติแทน')}
async function subVip(p){await api('/api/vip/subscribe',{method:'POST',body:JSON.stringify({plan:p})});refresh()}
async function loadOrders(type='all'){if(!need())return;let j=await api('/api/orders?type='+type);ordersBox.innerHTML=j.orders.length?`<table><tr><th>สินค้า</th><th>สถานะ</th><th>ยอด</th><th>Fee</th><th>จัดการ</th></tr>${j.orders.map(o=>`<tr><td>${o.item_title}</td><td>${status(o.status)}</td><td>${money(o.amount,o.currency)}</td><td>${actions(o)}</td></tr>`).join('')}</table>`:'<div class="notice">ยังไม่มี Order</div>'}function status(s){return {WAIT_SHIPPING:'รอจัดส่ง',SHIPPED:'จัดส่งแล้ว',DELIVERED:'รอยืนยัน',COMPLETED:'สำเร็จ',DISPUTE:'ข้อพิพาท',REFUNDED:'คืนเงิน'}[s]||s}function actions(o){let h='';if(o.seller_id==me?.id&&o.status=='WAIT_SHIPPING')h+=`<input id="co${o.id}" placeholder="ขนส่ง"><input id="tr${o.id}" placeholder="เลขพัสดุ"><button onclick="ship(${o.id})">จัดส่ง</button>`;if([o.seller_id,o.buyer_id].includes(me?.id)&&['SHIPPED','DELIVERED'].includes(o.status))h+=`<button class="green" onclick="confirmO(${o.id})">ยืนยันซื้อขายสำเร็จ</button>`;if([o.seller_id,o.buyer_id].includes(me?.id)&&!['COMPLETED','REFUNDED'].includes(o.status))h+=`<input id="dp${o.id}" placeholder="เหตุผล"><button class="danger" onclick="dispute(${o.id})">ข้อพิพาท</button>`;return h||'-'}async function ship(id){await api('/api/orders/'+id+'/ship',{method:'POST',body:JSON.stringify({shipping_company:$('co'+id).value,tracking_number:$('tr'+id).value})});loadOrders()}async function confirmO(id){await api('/api/orders/'+id+'/confirm',{method:'POST'});alert('ยืนยันแล้ว ถ้าครบสองฝ่าย ระบบจะปล่อยเงินให้ผู้ขาย');loadOrders();refresh()}async function dispute(id){let fd=new FormData();fd.append('reason',$('dp'+id).value);await fetch('/api/orders/'+id+'/dispute',{method:'POST',body:fd});loadOrders()}
async function estimatePrice(){if(!need())return;let fs=[...estPhotos.files];if(fs.length<1||fs.length>6)return alert('ใส่รูป 1-6 รูป');let fd=new FormData();fd.append('title',estTitle.value);fd.append('category',estCat.value);fd.append('condition',estCond.value);fd.append('notes',estNotes.value);fs.forEach(f=>fd.append('photos',f));let r=await fetch('/api/ai/price-estimate',{method:'POST',body:fd}),j=await r.json();let e=j.estimate;estResult.innerHTML=`<div class="notice success"><h3>${e.estimated_min.toLocaleString()} - ${e.estimated_max.toLocaleString()} บาท</h3><p>ค่ากลาง ${e.estimated_mid.toLocaleString()} | ความมั่นใจ ${e.confidence}</p><div class="thumbs">${e.photos.map(p=>`<img src="${p}">`).join('')}</div></div>`;loadEstHistory()}async function loadEstHistory(){if(!me)return;let j=await api('/api/ai/price-estimates');estHistory.innerHTML=j.estimates.map(e=>`<div class="notice">${e.title}: ${e.estimated_min.toLocaleString()} - ${e.estimated_max.toLocaleString()} บาท</div>`).join('')||'<div class="notice">ยังไม่มีประวัติ</div>'}
function renderProfile(){if(!me)return;profileBox.innerHTML=`<div class="notice success">${me.username}</div>`;pName.value=me.display_name||'';pEmail.value=me.email||'';pBio.value=me.bio||'';pAvatar.value=me.avatar_url||'';trustBox.innerHTML=`<div class="price">${me.trust_rate||0}%</div><div>สำเร็จ ${me.trust_completed_sales||0}/${me.trust_total_orders||0} รายการ</div>`}async function saveProfile(){me=(await api('/api/me/profile',{method:'PUT',body:JSON.stringify({display_name:pName.value,email:pEmail.value,bio:pBio.value,avatar_url:pAvatar.value})})).user;refresh()}

async function loadReviews(){
  const q = encodeURIComponent(reviewSearch?.value || '');
  const j = await api('/api/reviews/users?q=' + q);
  reviewUsersBox.innerHTML = j.users.length ? `<table><tr><th>ID</th><th>ชื่อผู้ใช้</th><th>ซื้อ/ขาย</th><th>อัตราสำเร็จ</th><th>ดูข้อมูล</th></tr>${j.users.map(u=>`<tr><td>#${u.id}</td><td><button class="light" onclick="loadReviewDetail(${u.id})">${u.display_name||u.username}</button><br><span class="muted">@${u.username}</span></td><td>ซื้อ ${u.bought_count} / ขาย ${u.sold_count}</td><td>${u.trust_rate||0}%<br><span class="muted">สำเร็จ ${u.trust_completed_sales||0}/${u.trust_total_orders||0}</span></td><td><button onclick="loadReviewDetail(${u.id})">รายละเอียด</button></td></tr>`).join('')}</table>` : '<div class="notice">ไม่พบข้อมูลที่ตรงกัน</div>';
  reviewDetailBox.innerHTML = '';
}
async function loadReviewDetail(id){
  const j = await api('/api/reviews/users/' + id);
  const u = j.user;
  reviewDetailBox.innerHTML = `<div class="panel content" style="margin-top:18px"><h2>ข้อมูลรีวิว: ${u.display_name||u.username} (#${u.id})</h2><div class="grid"><div class="card content"><h3>อัตราความสำเร็จ</h3><div class="price">${u.trust_rate||0}%</div><p class="muted">ซื้อขายสำเร็จ ${u.trust_completed_sales||0}/${u.trust_total_orders||0} รายการ</p></div><div class="card content"><h3>ประวัติ</h3><div>ซื้อ: <b>${j.summary.bought_count}</b></div><div>ขาย: <b>${j.summary.sold_count}</b></div><div>ทั้งหมด: <b>${j.summary.total_trades}</b></div></div></div><h3>รายการซื้อขาย/ประมูลที่ผ่านมา</h3>${j.history.length ? `<table><tr><th>สินค้า</th><th>รายละเอียด</th><th>ราคาปิด</th><th>ผู้ชนะ</th><th>สถานะ</th><th>เวลา</th></tr>${j.history.map(h=>`<tr><td><b>${h.item_title||'-'}</b><br><span class="muted">${h.level||''} / ${h.method||''}</span></td><td>${h.description||'-'}</td><td>${money(h.close_price,h.currency||'Credit')}</td><td>${h.winner_name||'-'}</td><td>${status(h.status)}</td><td>${h.created_at?new Date(h.created_at).toLocaleString('th-TH'):'-'}</td></tr>`).join('')}</table>` : '<div class="notice">ยังไม่มีประวัติซื้อขาย</div>'}</div>`;
}

function showAdmin(){if(!me){Object.keys(pages).forEach(p=>$(p)?.classList.add('hidden'));login.classList.remove('hidden');title.textContent=pages.login;desc.textContent='BidMarket';refresh();return}if(me.role!='admin')return alert('เฉพาะ Admin');Object.keys(pages).forEach(p=>$(p)?.classList.add('hidden'));admin.classList.remove('hidden');title.textContent=pages.admin;desc.textContent='BidMarket';loadAdmin()}async function loadAdmin(){let e=await api('/api/admin/escrow');let pj=await api('/api/admin/payments');adminBox.innerHTML=`<div class="grid"><div class="card content"><h3>เงินพัก Escrow</h3><div class="price">${money(e.held,'Credit')}</div></div><div class="card content"><h3>รอจัดส่ง</h3><div class="price">${e.waitShipping}</div></div><div class="card content"><h3>ข้อพิพาท</h3><div class="price">${e.disputes}</div></div></div><h3>ตรวจสอบสลิปเติม Credit</h3>${pj.payments.length?`<table><tr><th>ผู้ใช้</th><th>ยอด</th><th>Credit</th><th>สถานะ</th><th>สลิป</th><th>จัดการ</th></tr>${pj.payments.map(p=>`<tr><td>${p.user?.username||p.user_id}</td><td>${p.baht_amount||0} บาท</td><td>${p.credit_amount}</td><td>${payStatus(p.status)}</td><td>${p.slip_url?`<a href="${p.slip_url}" target="_blank">ดูสลิป</a>`:'-'}</td><td>${p.status==='approved'?'-':`<button class="green" onclick="adminApprovePay('${p.id}')">อนุมัติ</button><button class="danger" onclick="adminRejectPay('${p.id}')">ปฏิเสธ</button>`}</td></tr>`).join('')}</table>`:'<div class="notice">ยังไม่มีรายการเติม Credit</div>'}<h3>คำสั่งซื้อ / Escrow</h3><table><tr><th>สินค้า</th><th>สถานะ</th><th>ยอด</th><th>Fee</th><th>จัดการ</th></tr>${e.orders.map(o=>`<tr><td>${o.item_title}</td><td>${status(o.status)}</td><td>${money(o.amount,o.currency)}</td><td>Escrow ${o.service_fee||0} / Sale ${o.sale_success_fee||0} / คืน ${o.escrow_cashback||0}</td><td><button onclick="adminRel(${o.id})">ปล่อยเงิน</button><button class="danger" onclick="adminRef(${o.id})">คืนเงิน</button></td></tr>`).join('')}</table>`}
function payStatus(s){return {pending_slip:'รอสลิป',waiting_admin:'รอตรวจสอบ',approved:'อนุมัติแล้ว',rejected:'ปฏิเสธ'}[s]||s}
async function adminApprovePay(id){await api('/api/admin/payments/'+id+'/approve',{method:'POST',body:JSON.stringify({})});alert('อนุมัติแล้ว ระบบเพิ่ม Credit ให้ผู้ใช้แล้ว');loadAdmin()}
async function adminRejectPay(id){let note=prompt('เหตุผลที่ปฏิเสธ')||'';await api('/api/admin/payments/'+id+'/reject',{method:'POST',body:JSON.stringify({note})});loadAdmin()}
async function adminRel(id){await api('/api/admin/orders/'+id+'/release',{method:'POST'});loadAdmin()}async function adminRef(id){await api('/api/admin/orders/'+id+'/refund',{method:'POST'});loadAdmin()}

function toggleFloatingChat(){
  if(!me){show('login');return}
  chatWindow.classList.toggle('hidden');
}
function sendFloatingChat(){
  if(!me){show('login');return}
  const text=(floatingChatInput.value||'').trim();
  if(!text)return;
  floatingChatMessages.insertAdjacentHTML('beforeend',`<div class="chatBubble me"><b>${me.display_name||me.username}:</b> ${escapeHtml(text)}</div>`);
  floatingChatInput.value='';
  floatingChatMessages.scrollTop=floatingChatMessages.scrollHeight;
}
function escapeHtml(t){return String(t).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}

setInterval(()=>{if(selected&&!room.classList.contains('hidden'))openRoom(selected)},8000);show('home');