
require('dotenv').config();
const express=require('express'), session=require('express-session'), bcrypt=require('bcryptjs'), path=require('path'), fs=require('fs'), multer=require('multer');
const {v4:uuidv4}=require('uuid');
const app=express(), PORT=process.env.PORT||3000;
const dataDir=process.env.DATA_DIR||path.join(__dirname,'data'), dbFile=path.join(dataDir,'db.json'), uploadDir=process.env.UPLOAD_DIR||path.join(__dirname,'public','uploads');
fs.mkdirSync(dataDir,{recursive:true});fs.mkdirSync(uploadDir,{recursive:true});
const now=()=>Date.now(); const img='https://images.unsplash.com/photo-1560472354-b33ff0c44a43?q=80&w=1200&auto=format&fit=crop';
function seed(){const hash=bcrypt.hashSync('1234',10), t=now();return {next:{u:3,a:4,ad:2,tx:1,pay:1,w:1,rev:1},users:[
{id:1,username:'demo',email:'demo@local',password_hash:hash,role:'admin',status:'active',display_name:'Demo Admin',avatar_url:'',bio:'',phone:'',address:'',coin:5000000,credit:50000,token:20,vip_until:t+365*86400000,vip_plan:'yearly',successful_credit_sales:1,created_at:t,last_login_at:null},
{id:2,username:'seller',email:'seller@local',password_hash:hash,role:'user',status:'active',display_name:'VIP Seller',avatar_url:'',bio:'ตัวอย่างผู้ขาย VIP',phone:'',address:'',coin:2000000,credit:30000,token:5,vip_until:t+180*86400000,vip_plan:'halfyear',successful_credit_sales:1,created_at:t,last_login_at:null}],
auctions:[
{id:1,seller_id:1,level:'general',method:'forward',currency:'coin',title:'iPhone 15 Pro Max',description:'ประมูลทั่วไปด้วย Coin',category:'มือถือ',image_url:'https://images.unsplash.com/photo-1695048133142-1a20484d2569?q=80&w=1200&auto=format&fit=crop',media_type:'image',start_price:2850000,current_bid:2850000,winner_id:null,last_bidder_id:null,bids_count:34,sealed_bids:[],participants:[],bidder_last_amounts:{},vip_entries:[],auction_chats:[],english_started:false,english_reset:30,english_step:0,time_left:0,start_at:t-3600000,end_at:t+86400000,auction_end_at:null,vip_entry_min_credit:0,vip_entry_fee_percent:0,status:'active',created_at:t},
{id:2,seller_id:1,level:'general',method:'english',currency:'credit',title:'PlayStation 5 Slim',description:'ตั้งเวลาเริ่มประมูลล่วงหน้า',category:'เกม',image_url:'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?q=80&w=1200&auto=format&fit=crop',media_type:'image',start_price:2600,current_bid:2600,winner_id:null,last_bidder_id:null,bids_count:0,sealed_bids:[],participants:[],bidder_last_amounts:{},vip_entries:[],auction_chats:[],english_started:false,english_reset:30,english_step:200,time_left:0,start_at:t+900000,end_at:null,auction_end_at:t+4500000,vip_entry_min_credit:0,vip_entry_fee_percent:0,status:'active',created_at:t},
{id:3,seller_id:2,level:'vip',method:'forward',currency:'credit',title:'Rolex Submariner Vintage',description:'VIP Zone ต้องใส่ Credit เข้าร่วมก่อนประมูล',category:'ของสะสม',image_url:'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?q=80&w=1200&auto=format&fit=crop',media_type:'image',start_price:10000,current_bid:10000,winner_id:null,last_bidder_id:null,bids_count:0,sealed_bids:[],participants:[],bidder_last_amounts:{},vip_entries:[],auction_chats:[],english_started:false,english_reset:30,english_step:0,time_left:0,start_at:t-1800000,end_at:t+7200000,auction_end_at:null,vip_entry_min_credit:7000,vip_entry_fee_percent:5,status:'active',created_at:t}],
ads:[{id:1,owner_id:1,title:'BidMarket Premium Deals',description:'ดูดีลพิเศษสำหรับสมาชิก',type:'image',media_url:'https://images.unsplash.com/photo-1556745757-8d76bdb6984b?q=80&w=1200&auto=format&fit=crop',budget:100,remaining_budget:100,cost_per_click:1,views:0,active:true,viewed_by:[],created_at:t}],
transactions:[],payments:[],winners:[],favorites:[],messages:[],company_revenues:[]};}
function migrate(d){d.next=d.next||{};['u','a','ad','tx','pay','w','rev'].forEach(k=>d.next[k]=d.next[k]||1);['users','auctions','ads','transactions','payments','winners','favorites','messages','company_revenues'].forEach(k=>d[k]=d[k]||[]);d.users.forEach(u=>{u.role=u.role||(u.username==='demo'?'admin':'user');u.status=u.status||'active';u.display_name=u.display_name||u.username;u.avatar_url=u.avatar_url||'';u.bio=u.bio||'';u.phone=u.phone||'';u.address=u.address||''});d.auctions.forEach(a=>{a.start_at=a.start_at||a.created_at||now();a.media_type=a.media_type||'image';a.participants=a.participants||[];a.bidder_last_amounts=a.bidder_last_amounts||{};a.vip_entries=a.vip_entries||[];a.auction_chats=a.auction_chats||[];a.vip_entry_min_credit=Number(a.vip_entry_min_credit||0);a.vip_entry_fee_percent=Number(a.vip_entry_fee_percent||0)})}
function load(){if(!fs.existsSync(dbFile))fs.writeFileSync(dbFile,JSON.stringify(seed(),null,2));let d=JSON.parse(fs.readFileSync(dbFile));migrate(d);return d}
let db=load(); const save=()=>fs.writeFileSync(dbFile,JSON.stringify(db,null,2)); const id=k=>{let v=db.next[k]||1;db.next[k]=v+1;return v}
const U=id=>db.users.find(u=>u.id==id), UN=n=>db.users.find(u=>u.username===n), vip=u=>!!(u&&Number(u.vip_until||0)>now());
function pub(u){return u&&{id:u.id,username:u.username,email:u.email,role:u.role,status:u.status,display_name:u.display_name||u.username,avatar_url:u.avatar_url||'',bio:u.bio||'',phone:u.phone||'',address:u.address||'',coin:u.coin,credit:u.credit,token:u.token,vip_until:u.vip_until,vip_plan:u.vip_plan,is_vip:vip(u)}}
function auth(req,res,next){if(!req.session.userId)return res.status(401).json({error:'กรุณาเข้าสู่ระบบก่อน'});let u=U(req.session.userId);if(!u||u.status!=='active')return res.status(403).json({error:'บัญชีถูกระงับ'});next()}
function admin(req,res,next){let u=U(req.session.userId);if(!u||u.role!=='admin')return res.status(403).json({error:'เฉพาะ Admin'});next()}
function reqVip(req,res,next){let u=U(req.session.userId);if(!vip(u))return res.status(403).json({error:'ต้องเป็นสมาชิก VIP'});req.user=u;next()}
function tx(uid,type,amount,currency,note=''){db.transactions.unshift({id:id('tx'),user_id:uid,type,amount,currency,note,created_at:now()})}
function bal(uid,c,delta,type,note=''){let u=U(uid);if(!u)throw Error('ไม่พบผู้ใช้');if(!['coin','credit','token'].includes(c))throw Error('สกุลเงินไม่ถูกต้อง');if(Number(u[c]||0)+delta<0)throw Error('ยอดเงินไม่พอ');u[c]=Number(u[c]||0)+delta;tx(uid,type,delta,c,note)}
function seller(a){return U(a.seller_id)?.username||'unknown'} function auc(a,viewer){let e=viewer?(a.vip_entries||[]).find(x=>x.user_id==viewer):null;return {...a,seller_name:seller(a),seller_is_vip:vip(U(a.seller_id)),winner_name:a.winner_id?U(a.winner_id)?.username:null,sealed_count:(a.sealed_bids||[]).length,participant_count:Object.keys(a.bidder_last_amounts||{}).length,is_started:now()>=Number(a.start_at||0),time_until_start:Math.max(0,Number(a.start_at||0)-now()),viewer_vip_entry:e||null}}
function revenue(a,type,amount,currency,note=''){if(amount>0)db.company_revenues.unshift({id:id('rev'),auction_id:a?.id||null,item_title:a?.title||'',type,amount,currency,note,created_at:now()})}
app.use(express.json({limit:'25mb'})); app.use(express.urlencoded({extended:true})); app.use(session({secret:process.env.SESSION_SECRET||'dev-secret',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',maxAge:7*86400000}})); app.use(express.static(path.join(__dirname,'public'))); app.use('/uploads',express.static(uploadDir));
const upload=multer({storage:multer.diskStorage({destination:(_,__,cb)=>cb(null,uploadDir),filename:(_,f,cb)=>cb(null,`${Date.now()}-${uuidv4()}${path.extname(f.originalname)}`)}),limits:{fileSize:50*1024*1024}});
app.post('/api/register',(req,res)=>{let {username,email,password}=req.body;if(!username||!email||!password)return res.status(400).json({error:'กรอกข้อมูลให้ครบ'});if(UN(username.trim()))return res.status(400).json({error:'ชื่อผู้ใช้นี้มีอยู่แล้ว'});let u={id:id('u'),username:username.trim(),email:email.trim(),password_hash:bcrypt.hashSync(password,10),role:'user',status:'active',display_name:username.trim(),avatar_url:'',bio:'',phone:'',address:'',coin:0,credit:0,token:0,vip_until:0,vip_plan:null,successful_credit_sales:0,created_at:now(),last_login_at:null};db.users.push(u);req.session.userId=u.id;save();res.json({user:pub(u)})});
app.post('/api/login',(req,res)=>{let u=UN(req.body.username);if(!u||!bcrypt.compareSync(req.body.password||'',u.password_hash))return res.status(401).json({error:'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง'});if(u.status!=='active')return res.status(403).json({error:'บัญชีถูกระงับ'});u.last_login_at=now();req.session.userId=u.id;save();res.json({user:pub(u)})});
app.post('/api/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true}))); app.get('/api/me',(req,res)=>res.json({user:req.session.userId?pub(U(req.session.userId)):null}));
app.put('/api/me/profile',auth,(req,res)=>{let u=U(req.session.userId);u.display_name=String(req.body.display_name||u.username).trim();u.email=String(req.body.email||u.email).trim();u.bio=String(req.body.bio||'').trim();u.phone=String(req.body.phone||'').trim();u.address=String(req.body.address||'').trim();if(req.body.avatar_url!==undefined)u.avatar_url=String(req.body.avatar_url||'').trim();save();res.json({user:pub(u)})});
app.put('/api/me/password',auth,(req,res)=>{let u=U(req.session.userId);if(!bcrypt.compareSync(req.body.current_password||'',u.password_hash))return res.status(400).json({error:'รหัสผ่านเดิมไม่ถูกต้อง'});if(String(req.body.new_password||'').length<6)return res.status(400).json({error:'รหัสใหม่อย่างน้อย 6 ตัว'});u.password_hash=bcrypt.hashSync(req.body.new_password,10);save();res.json({ok:true})});
app.post('/api/upload',auth,upload.single('file'),(req,res)=>res.json({url:`/uploads/${req.file.filename}`}));
app.post('/api/vip/subscribe',auth,(req,res)=>{let plans={monthly:[30,480],halfyear:[180,2400],yearly:[365,4320]}, p=plans[req.body.plan];if(!p)return res.status(400).json({error:'แพ็กเกจไม่ถูกต้อง'});let u=U(req.session.userId),base=vip(u)?u.vip_until:now();u.vip_until=base+p[0]*86400000;u.vip_plan=req.body.plan;tx(u.id,'สมัคร VIP',p[1],'baht',req.body.plan);save();res.json({user:pub(u)})});
app.post('/api/wallet/buy-coin',auth,(req,res)=>{let b=Number(req.body.baht);if(!b)return res.status(400).json({error:'จำนวนเงินไม่ถูกต้อง'});bal(req.session.userId,'coin',b*100,'ซื้อ Coin',`${b} บาท`);save();res.json({user:pub(U(req.session.userId))})});
app.post('/api/payments/create-credit-topup',auth,(req,res)=>{let b=Number(req.body.baht);if(!b||b<5)return res.status(400).json({error:'เติมขั้นต่ำ 5 บาท'});let p={id:uuidv4(),user_id:req.session.userId,baht_amount:b,credit_amount:Math.floor(b/5),status:'pending',created_at:now()};db.payments.push(p);save();res.json({payment_id:p.id,credit_amount:p.credit_amount})});
app.post('/api/payments/mock-confirm',auth,(req,res)=>{let p=db.payments.find(x=>x.id===req.body.payment_id&&x.user_id===req.session.userId);if(!p)return res.status(404).json({error:'ไม่พบรายการ'});if(p.status!=='paid'){p.status='paid';p.paid_at=now();bal(p.user_id,'credit',p.credit_amount,'เติม Credit',`ชำระ ${p.baht_amount} บาท`);save()}res.json({ok:true,user:pub(U(req.session.userId))})});
app.post('/api/wallet/transfer',auth,(req,res)=>{try{let to=UN(req.body.to_username), s=U(req.session.userId), amount=Number(req.body.amount);if(!to)throw Error('ไม่พบบัญชีผู้รับ'); if(req.body.currency==='credit'){if(amount<20)throw Error('Credit โอนขั้นต่ำ 20');let fee=Math.ceil(amount*.1);bal(s.id,'credit',-(amount+fee),'โอน Credit',`ถึง ${to.username}`);bal(to.id,'credit',amount,'รับ Credit',`จาก ${s.username}`)}else{if(amount<1)throw Error('Token โอนขั้นต่ำ 1');let fee=amount*25;bal(s.id,'token',-amount,'โอน Token',`ถึง ${to.username}`);bal(s.id,'credit',-fee,'ค่าธรรมเนียมโอน Token',`${fee}`);bal(to.id,'token',amount,'รับ Token',`จาก ${s.username}`)}save();res.json({user:pub(s)})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/wallet/withdraw',auth,(req,res)=>{try{let amount=Number(req.body.amount), c=req.body.currency;if(!['credit','token'].includes(c))throw Error('ถอนได้เฉพาะ Credit/Token');bal(req.session.userId,c,-amount,'คำขอถอนเงิน',req.body.note||'รอตรวจสอบ');save();res.json({ok:true,user:pub(U(req.session.userId))})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/auctions',(req,res)=>res.json({auctions:db.auctions.filter(a=>a.status==='active'&&a.level===(req.query.level||'general')).sort((a,b)=>b.created_at-a.created_at).map(a=>auc(a,req.session.userId))}));
app.get('/api/auctions/:id',(req,res)=>{let a=db.auctions.find(x=>x.id==req.params.id);if(!a)return res.status(404).json({error:'ไม่พบ'});res.json({auction:auc(a,req.session.userId)})});
app.post('/api/auctions',auth,(req,res)=>{let u=U(req.session.userId), start=Number(req.body.start_price), {level,method,currency,title,description,category,image_url,media_type}=req.body;if(!title||!start)return res.status(400).json({error:'กรอกชื่อสินค้าและราคาเริ่มต้น'});let startAt=req.body.start_at?new Date(req.body.start_at).getTime():now();if(!startAt||startAt<now()-60000)startAt=now();if(startAt>now()+30*86400000)return res.status(400).json({error:'ตั้งเวลาเริ่มล่วงหน้าได้ไม่เกิน 30 วัน'});if(level==='general'&&!['forward','english'].includes(method))return res.status(400).json({error:'ทั่วไปใช้ Forward/English'});if(level==='general'&&!['coin','credit'].includes(currency))return res.status(400).json({error:'ทั่วไปใช้ Coin/Credit'});let vipMin=0,vipFee=0;if(level==='vip'){if(!vip(u))return res.status(403).json({error:'ลง VIP ต้องเป็นสมาชิก VIP'});vipMin=Number(req.body.vip_entry_min_credit);vipFee=Number(req.body.vip_entry_fee_percent);if(!vipMin||vipMin<100||vipMin>1000000)return res.status(400).json({error:'Credit ขั้นต่ำ 100-1,000,000'});if(method!=='sealed'&&(!vipFee||vipFee<1||vipFee>10))return res.status(400).json({error:'Credit ประมูล 1-10%'})}let end_at=startAt+86400000,auction_end_at=null,eReset=30,eStep=0;if(method==='sealed'){let h=Number(req.body.sealed_hours);if(!h||h<2||h>720)return res.status(400).json({error:'ปิดซอง 2-720 ชม.'});end_at=startAt+h*3600000}if(method==='english'){let h=Number(req.body.english_duration_hours);eReset=Number(req.body.english_reset);eStep=Number(req.body.english_step);if(!h||h<1||h>720)return res.status(400).json({error:'เคาะราคา 1-720 ชม.'});if(eReset<10||eReset>60)return res.status(400).json({error:'นับถอยหลัง 10-60 วิ'});if(!eStep||eStep<Math.ceil(start*.05))return res.status(400).json({error:`ราคาเคาะขั้นต่ำ ${Math.ceil(start*.05)}`});auction_end_at=startAt+h*3600000;end_at=null}let a={id:id('a'),seller_id:u.id,level,method,currency,title,description:description||'',category:category||'อื่นๆ',image_url:image_url||img,media_type:media_type||'image',start_price:start,current_bid:method==='sealed'?0:start,winner_id:null,last_bidder_id:null,bids_count:0,sealed_bids:[],participants:[],bidder_last_amounts:{},vip_entries:[],auction_chats:[],english_started:false,english_reset:eReset,english_step:eStep,time_left:0,start_at:startAt,end_at,auction_end_at,vip_entry_min_credit:vipMin,vip_entry_fee_percent:method==='sealed'?0:vipFee,status:'active',created_at:now()};db.auctions.push(a);save();res.json({auction:auc(a,u.id)})});
app.post('/api/auctions/:id/join',auth,(req,res)=>{let a=db.auctions.find(x=>x.id==req.params.id&&x.status==='active'), u=U(req.session.userId);if(!a)return res.status(404).json({error:'ไม่พบการประมูล'});if(a.seller_id===u.id)return res.status(400).json({error:'ผู้ขายเข้าร่วมสินค้าตัวเองไม่ได้'});if(a.level==='vip'){if(!vip(u))return res.status(403).json({error:'ต้องเป็น VIP'});let amount=Number(req.body.credit_amount), reqd=Math.max(Number(a.vip_entry_min_credit||0),Math.ceil(Number(a.start_price)*.7));if(!amount||amount<reqd)return res.status(400).json({error:`ต้องใส่ Credit อย่างน้อย ${reqd}`});if(u.credit<amount)return res.status(400).json({error:'Credit ไม่พอ'});let e=a.vip_entries.find(x=>x.user_id===u.id);if(e)e.credit_amount=amount;else a.vip_entries.push({user_id:u.id,credit_amount:amount,created_at:now()})}if(!a.participants.includes(u.id))a.participants.push(u.id);save();res.json({auction:auc(a,u.id)})});
app.post('/api/auctions/:id/bid',auth,(req,res)=>{try{let a=db.auctions.find(x=>x.id==req.params.id&&x.status==='active'), u=U(req.session.userId);if(!a)throw Error('ไม่พบการประมูล');if(now()<a.start_at)throw Error('ยังไม่ถึงเวลาเริ่มประมูล');if(a.seller_id===u.id)throw Error('ผู้ขายประมูลสินค้าตัวเองไม่ได้');if(a.level==='vip'&&!a.vip_entries.find(e=>e.user_id===u.id))throw Error('กรุณาเข้าร่วม VIP และระบุ Credit ก่อน');if(!a.participants.includes(u.id))a.participants.push(u.id);if(a.method==='english'){let amount=Number(a.english_step);bal(u.id,a.currency,-amount,'เคาะราคา',a.title);a.current_bid+=amount;a.winner_id=u.id;a.last_bidder_id=u.id;a.bids_count++;a.english_started=true;a.time_left=a.english_reset;a.bidder_last_amounts[u.id]=a.current_bid}else if(a.method==='sealed'){let amount=Number(req.body.amount);if(!amount)throw Error('กรุณาใส่ราคา');if(a.sealed_bids.some(b=>b.user_id===u.id))throw Error('ปิดซองเสนอได้ครั้งเดียว');bal(u.id,a.currency,-amount,'ส่งซอง',a.title);a.sealed_bids.push({user_id:u.id,amount,at:now()});a.bids_count++;a.bidder_last_amounts[u.id]=amount}else{let amount=Number(req.body.amount);if(!amount||amount<=a.current_bid)throw Error('ต้องเสนอราคาสูงกว่าปัจจุบัน');bal(u.id,a.currency,-(amount-a.current_bid),'เสนอราคา',a.title);a.current_bid=amount;a.winner_id=u.id;a.last_bidder_id=u.id;a.bids_count++;a.bidder_last_amounts[u.id]=amount}a.auction_chats.push({id:uuidv4(),system:true,text:`${u.display_name||u.username} เสนอราคาล่าสุด ${a.bidder_last_amounts[u.id]} ${a.currency}`,user_id:u.id,username:u.username,created_at:now()});save();res.json({auction:auc(a,u.id),user:pub(u)})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/auctions/:id/chat',auth,(req,res)=>{let a=db.auctions.find(x=>x.id==req.params.id&&x.status==='active'),u=U(req.session.userId);if(!a)return res.status(404).json({error:'ไม่พบ'});let text=String(req.body.text||'').trim();if(!text)return res.status(400).json({error:'กรุณาพิมพ์ข้อความ'});if(!a.participants.includes(u.id))a.participants.push(u.id);a.auction_chats.push({id:uuidv4(),system:false,text,user_id:u.id,username:u.username,display_name:u.display_name||u.username,created_at:now()});save();res.json({ok:true})});
function closeA(a){if(a.status!=='active')return null;let winnerId=a.winner_id||a.last_bidder_id, price=Number(a.current_bid||0);if(a.method==='sealed'){let bids=[...a.sealed_bids].sort((x,y)=>y.amount-x.amount);if(bids[0]){winnerId=bids[0].user_id;price=bids[0].amount}}let w=winnerId?U(winnerId):null,s=U(a.seller_id), service=0,vipTotal=0,vipCompany=0,sellerVip=0;if(w&&s&&price>0){if(a.currency==='credit'){let rate=vip(s)?.04:.07;service=Math.round(price*rate);revenue(a,'ค่าบริการเว็บไซต์',service,'credit',`${rate*100}%`)}else if(a.currency==='coin'){service=Math.round(price*.25);revenue(a,'ค่าบริการ Coin',service,'coin','25%')}bal(s.id,a.currency,price-service,'รับเงินจากการประมูล',a.title);if(a.currency==='credit'&&price>=10000)s.successful_credit_sales++;if(a.currency==='credit'){let tr=Math.floor(price/1000);if(tr>0)bal(w.id,'token',tr,'รับ Token จากการชนะประมูล',a.title)}if(a.level==='vip'&&a.method!=='sealed'&&Number(a.vip_entry_fee_percent)>0){Object.entries(a.bidder_last_amounts||{}).forEach(([uid,amt])=>{uid=Number(uid);if(uid===w.id)return;let pen=Math.round(Number(amt)*Number(a.vip_entry_fee_percent)/100);if(pen>0){bal(uid,'credit',-pen,'Credit ประมูล VIP',a.title);vipTotal+=pen}});vipCompany=Math.round(vipTotal*.5);sellerVip=vipTotal-vipCompany;if(vipCompany>0)revenue(a,'ส่วนแบ่ง Credit ประมูล VIP',vipCompany,'credit','50%');if(sellerVip>0)bal(s.id,'credit',sellerVip,'รับ Credit ประมูล VIP',a.title)}}a.status='closed';let r={id:id('w'),auction_id:a.id,item_title:a.title,level:a.level,winner_id:w?w.id:null,winner_name:w?w.username:'ไม่มีผู้ชนะ',price,currency:a.currency,method:a.method,service_fee:service,vip_penalty_total:vipTotal,vip_penalty_company:vipCompany,seller_vip_penalty_income:sellerVip,closed_at:now(),created_at:now()};db.winners.unshift(r);save();return r}
app.post('/api/auctions/:id/close',auth,(req,res)=>{let a=db.auctions.find(x=>x.id==req.params.id),u=U(req.session.userId);if(!a)return res.status(404).json({error:'ไม่พบ'});if(a.seller_id!==u.id&&u.role!=='admin')return res.status(403).json({error:'เฉพาะผู้ขายหรือ Admin'});res.json({result:closeA(a)})});
app.get('/api/favorites',auth,(req,res)=>{let ids=db.favorites.filter(f=>f.user_id===req.session.userId).map(f=>f.auction_id);res.json({favorite_ids:ids,auctions:db.auctions.filter(a=>ids.includes(a.id)&&a.status==='active').map(a=>auc(a,req.session.userId))})});
app.post('/api/favorites/:id',auth,(req,res)=>{let aid=Number(req.params.id);if(!db.favorites.find(f=>f.user_id===req.session.userId&&f.auction_id===aid))db.favorites.push({user_id:req.session.userId,auction_id:aid,created_at:now()});save();res.json({ok:true})});
app.delete('/api/favorites/:id',auth,(req,res)=>{let aid=Number(req.params.id);db.favorites=db.favorites.filter(f=>!(f.user_id===req.session.userId&&f.auction_id===aid));save();res.json({ok:true})});
app.get('/api/users/search',auth,(req,res)=>{let q=String(req.query.q||'').toLowerCase();res.json({users:db.users.filter(u=>u.id!==req.session.userId&&u.status==='active').filter(u=>!q||u.username.toLowerCase().includes(q)||(u.display_name||'').toLowerCase().includes(q)).slice(0,30).map(u=>({id:u.id,username:u.username,display_name:u.display_name||u.username,avatar_url:u.avatar_url||''}))})});
app.get('/api/messages/threads',auth,(req,res)=>{let my=req.session.userId,ids=new Set();db.messages.forEach(m=>{if(m.from_id===my)ids.add(m.to_id);if(m.to_id===my)ids.add(m.from_id)});res.json({threads:[...ids].map(pid=>{let u=U(pid),msgs=db.messages.filter(m=>(m.from_id===my&&m.to_id===pid)||(m.from_id===pid&&m.to_id===my)).sort((a,b)=>b.created_at-a.created_at);return{user:u&&{id:u.id,username:u.username,display_name:u.display_name||u.username,avatar_url:u.avatar_url||''},last_message:msgs[0]}}).filter(x=>x.user)})});
app.get('/api/messages/:id',auth,(req,res)=>{let other=Number(req.params.id),my=req.session.userId;res.json({messages:db.messages.filter(m=>(m.from_id===my&&m.to_id===other)||(m.from_id===other&&m.to_id===my)).sort((a,b)=>a.created_at-b.created_at),other:pub(U(other))})});
app.post('/api/messages/:id',auth,upload.single('file'),(req,res)=>{let to=U(req.params.id),text=String(req.body.text||'').trim(),image_url=req.file?`/uploads/${req.file.filename}`:'';if(!to)return res.status(404).json({error:'ไม่พบผู้รับ'});if(!text&&!image_url)return res.status(400).json({error:'กรุณาส่งข้อความหรือรูป'});let m={id:uuidv4(),from_id:req.session.userId,to_id:to.id,text,image_url,created_at:now()};db.messages.push(m);save();res.json({message:m})});
app.get('/api/ads',(req,res)=>res.json({ads:db.ads.filter(a=>a.active).map(a=>({...a,viewed:req.session.userId?a.viewed_by.includes(req.session.userId):false}))}));
app.post('/api/ads',reqVip,upload.single('file'),(req,res)=>{try{let b=Number(req.body.budget),cpc=Number(req.body.cost_per_click);if(cpc<.1)throw Error('ค่าคลิกขั้นต่ำ 0.1 Credit');bal(req.user.id,'credit',-b,'ลงโฆษณา',req.body.title);let a={id:id('ad'),owner_id:req.user.id,title:req.body.title,description:req.body.description||'',type:req.body.type||'image',media_url:req.file?`/uploads/${req.file.filename}`:(req.body.media_url||img),budget:b,remaining_budget:b,cost_per_click:cpc,views:0,active:true,viewed_by:[],created_at:now()};db.ads.unshift(a);save();res.json({ad:a})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/ads/:id/view',auth,(req,res)=>{try{let a=db.ads.find(x=>x.id==req.params.id&&x.active),u=U(req.session.userId);if(!a)throw Error('ไม่พบโฆษณา');if(a.viewed_by.includes(u.id))throw Error('ดูโฆษณานี้แล้ว');a.remaining_budget-=a.cost_per_click;a.views++;a.viewed_by.push(u.id);let reward=a.budget<=99?Math.floor(a.cost_per_click*.5*500):a.cost_per_click*.5,c=a.budget<=99?'coin':'credit';bal(u.id,c,reward,'ดูโฆษณา',a.title);save();res.json({reward,currency:c,ad:a,user:pub(u)})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/transactions',auth,(req,res)=>res.json({transactions:db.transactions.filter(t=>t.user_id===req.session.userId).slice(0,200)}));
app.get('/api/winners',(req,res)=>res.json({winners:db.winners.slice(0,100)}));
app.get('/api/admin/summary',auth,admin,(req,res)=>{let g=db.auctions.filter(a=>a.status==='active'&&a.level==='general').length,v=db.auctions.filter(a=>a.status==='active'&&a.level==='vip').length,total=db.company_revenues.reduce((s,r)=>s+Number(r.amount||0),0),monthly={};db.company_revenues.forEach(r=>{let d=new Date(r.created_at),k=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');monthly[k]=(monthly[k]||0)+Number(r.amount||0)});res.json({active:{general:g,vip:v,total:g+v},total_revenue:total,monthly_revenue:monthly})});
app.get('/api/admin/closed-auctions',auth,admin,(req,res)=>{let level=req.query.level||'all',rows=db.winners.filter(w=>level==='all'||w.level===level).sort((a,b)=>(b.closed_at||b.created_at)-(a.closed_at||a.created_at));res.json({rows:rows.slice(0,10),total:rows.length,page:1,size:10})});
app.get('/api/admin/users',auth,admin,(req,res)=>res.json({users:db.users.map(u=>pub(u))}));
app.put('/api/admin/users/:id',auth,admin,(req,res)=>{let u=U(req.params.id);if(!u)return res.status(404).json({error:'ไม่พบ'});if(req.body.status)u.status=req.body.status;if(req.body.role)u.role=req.body.role;if(req.body.add_credit)bal(u.id,'credit',Number(req.body.add_credit),'Admin เพิ่ม Credit','');save();res.json({user:pub(u)})});
app.get('*',(_,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
setInterval(()=>{let changed=false;db.auctions.filter(a=>a.status==='active'&&a.method==='english'&&a.english_started&&a.time_left>0).forEach(a=>{a.time_left--;changed=true;if(a.time_left<=0)closeA(a)});db.auctions.filter(a=>a.status==='active').forEach(a=>{if(a.method!=='english'&&a.end_at&&now()>a.end_at){closeA(a);changed=true}if(a.method==='english'&&!a.english_started&&a.auction_end_at&&now()>a.auction_end_at){closeA(a);changed=true}});if(changed)save()},1000);
app.listen(PORT,()=>console.log('BidMarket Advanced http://localhost:'+PORT));
